/**
 * Deterministic Synthetic IDs — generate stable, predictable IDs for
 * internally-created tool calls and results. Using deterministic IDs
 * (instead of randomUUID) enables:
 * 1. Stream recovery to recognize repeated/retried calls
 * 2. History deduplication after retries
 * 3. Debugging with readable, meaningful IDs
 *
 * Model-generated IDs are always used as-is. This module is only for
 * IDs we synthesize ourselves (injections, synthetic results, etc.)
 */

/**
 * Generate a deterministic synthetic ID.
 * Format: `kc_{prefix}_{round}_{index}`
 *
 * @param prefix - Purpose identifier (e.g., "inject", "diff", "ctx", "recovery")
 * @param round - Current conversation round/turn number
 * @param index - Index within the round (0-based, for multiple calls per round)
 */
export function syntheticId(
  prefix: string,
  round: number,
  index = 0,
): string {
  return `kc_${prefix}_r${round}_${index}`;
}

/**
 * Generate a synthetic ID for turn-summary injection.
 */
export function turnSummaryId(round: number): string {
  return syntheticId("summary", round);
}

/**
 * Generate a synthetic ID for turn-diff injection.
 */
export function turnDiffId(round: number): string {
  return syntheticId("diff", round);
}

/**
 * Generate a synthetic ID for context-remaining tool response.
 */
export function contextRemainingId(round: number): string {
  return syntheticId("ctx", round);
}

/**
 * Generate a synthetic ID for stream recovery / retry deduplication.
 * Uses request ID prefix + attempt for uniqueness across retries.
 */
export function recoveryId(
  requestId: string,
  attempt: number,
  callIndex: number,
): string {
  // Use first 8 chars of requestId to keep it short but identifiable
  const prefix = requestId.slice(0, 8);
  return `kc_recover_${prefix}_a${attempt}_${callIndex}`;
}

/**
 * Generate a synthetic ID for injected user messages (e.g., stop hook prompts).
 */
export function injectionId(round: number, purpose: string): string {
  return syntheticId(purpose, round);
}

/**
 * Check if a call ID is a synthetic one generated by us.
 */
export function isSyntheticId(id: string): boolean {
  return id.startsWith("kc_") || id === "__turn_diff__";
}

/**
 * Generate a batch of sequential synthetic IDs for multiple tool calls.
 */
export function syntheticIdBatch(
  prefix: string,
  round: number,
  count: number,
): string[] {
  return Array.from({ length: count }, (_, i) => syntheticId(prefix, round, i));
}
